name: Update repository settings

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    paths:
      - .github/settings.yml

jobs:
  probotSettings:
    runs-on: [ self-hosted ]
    steps:
      - uses: yemramirezca/repository-settings@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_LEVEL: debug
